# Generated by Django 5.1 on 2024-09-10 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('ip_address', models.GenericIPAddressField(default='0.0.0.0', verbose_name='IP')),
                ('description', models.TextField(default='no_description', max_length=255, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Server',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SystemInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_information', models.JSONField(verbose_name='host_information')),
                ('network', models.JSONField(verbose_name='network')),
                ('disk', models.JSONField(verbose_name='disk')),
                ('memory', models.JSONField(verbose_name='memory')),
                ('cpu', models.JSONField(verbose_name='cpu')),
                ('load_average', models.JSONField(verbose_name='load_average')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbr_srv_side.server')),
            ],
            options={
                'verbose_name': 'System Information',
                'managed': True,
            },
        ),
    ]
